//Jenkinsfile (Declarative Pipeline)
pipeline {
    agent {
        docker {
            image 'vitvizel/time-app-frontend-dev:2.0.0'
        }
    }
    stages {
        stage('Front-end') {
           
        
          
            }
        }
    }
