//Jenkinsfile Frontend (Declarative Pipeline)
pipeline {
    agent any

    stages {
        stage('Build Frontend'){
            steps {
            withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]) {    

                bat "docker build -f frontend\\Dockerfile -t vitvizel/timeapp-jenkins-frontend:1.0.${env.BUILD_NUMBER} ."
                bat "docker login -u $user -p $pass"
                bat "docker push vitvizel/timeapp-jenkins-frontend:1.0.${env.BUILD_NUMBER}"
            }

        }
           
        }
    }
}

// vitvizel/timeapp-jenkins: