//Jenkinsfile Frontend (Declarative Pipeline)
pipeline {
    agent docker

    stages {
        stage('Build Frontend'){
            steps {
            withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')]) {    

                bat "docker build -f Dockerfile -t frontend ."
            }

        }
           
        }
    }
}