parallel {
  
    stage('Parallel Test 1') {
        // the below jobs run sequentially one after the other
        build(job: "Time-app-Frontend",)
        build(job: "Time-app-Backend")
      
    }
   
       
    
}