//Jenkinsfile Backend Dev or Prod (Declarative Pipeline)

 pipeline 
{
    agent any
     

    options {
                buildDiscarder(logRotator(daysToKeepStr: '30'))
                disableConcurrentBuilds()
                timestamps()
                timeout(time: 20, unit: 'MINUTES')
}

    stages {
        stage('Build Backend')
        {
           
            steps 
            {
            
                bat "docker build -f api\\${params.Env}.Dockerfile -t vitvizel/timeapp-jenkins-backend:${params.Env}.${env.BUILD_NUMBER} ."
                bat "docker build -f api\\${params.Env}.Dockerfile -t vitvizel/timeapp-jenkins-backend:latest ."
                   echo " The environment is ${params.Env}"

            }
        }            
        stage('Push Backend')  
        { 
            steps 
            { 
                withCredentials([usernamePassword(credentialsId: 'dockerhub', passwordVariable: 'pass', usernameVariable: 'user')])   
                {  
                bat "docker login -u $user -p $pass"
                bat "docker push vitvizel/timeapp-jenkins-backend:${params.Env}.${env.BUILD_NUMBER}"
                bat "docker push vitvizel/timeapp-jenkins-backend:latest"
                }
            }

        }
           
        }
    

            post 
            {
                always 
                {
                deleteDir() /* clean up our workspace */
                }
            }
}
